baseURL = "https://www.codewrecks.com/"
languageCode = "en-us"
title = "Codewrecks"

googleAnalytics = "G-JNG3CSWEQT"

rssLimit = 200

[renderer]
unsafe = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
pagerSize = 10
preserveTaxonomyNames = true

enableRobotsTXT = true
pygmentsCodefences = true
enableEmoji = true
defaultContentLanguage = "en"

[params.info]
description = "Wrecks of code floating in the sea of internet"
title404 = "Nothing's here!"

[params.appearance]
defaultTheme = "gunmetal"

[params.assets]
favicon = "favicon.svg"
gopher = ""

[params.copyright]
prefix = ""
holder = "Ricci Gian Maria"
startYear = "2020"
suffix = ""

[params.settings]
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
showReadingTime = true
showLastmod = true

[params.services]
adsenseClient = "ca-pub-6590055118491660"

[params.opengraph.facebook]
admins = []
appID = ""
pageID = ""

[params.opengraph.twitter]
page = ""

[params.seo]
titleSeparator = "•"

[params.social]
email = "alkampfer@nablasoft.com"
github = "alkampfergit"
linkedin = "gianmariaricci"
twitter = "alkampfer"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Posts"
weight = -20
identifier = "posts"
url = "/post/"

[[menu.main]]
name = "Italian Blog"
weight = -15
identifier = "italian"
url = "/itablog/"

[[menu.main]]
name = "Categories"
weight = -10
identifier = "categories"
url = "/categories/"

[blackfriday]
hrefTargetBlank = true

[languages]
  [languages.en]
  languageCode = "en-us"
  languageName = "English"
  weight = 1

