baseURL = "https://www.codewrecks.com/itablog/"
languageCode = "it"
title = "Gian Maria Ricci"

googleAnalytics = "G-JNG3CSWEQT"

rssLimit = 200

[renderer]
unsafe = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
pagerSize = 10
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting
pygmentsCodefences = true

enableEmoji = true
defaultContentLanguage = "it"

[params.info]
description = "Articoli tecnici in italiano su sviluppo software e tecnologia"
title404 = "Niente qui!"

[params.appearance]
defaultTheme = "gunmetal"

[params.assets]
favicon = "favicon.ico"
gopher = ""

[params.copyright]
prefix = ""
holder = "Ricci Gian Maria"
startYear = "2020"
suffix = ""

[params.settings]
dateFormat = "02 Jan 2006"
listDateFormat = "02 Jan 2006"
archiveDateFormat = "02 Jan"
showReadingTime = true
showLastmod = true
accentColor = "#0d9488"

[params.opengraph.facebook]
admins = []
appID = ""
pageID = ""

[params.opengraph.twitter]
page = ""

[params.seo]
titleSeparator = "•"

[params.social]
email = "alkampfer@nablasoft.com"
github = "alkampfergit"
linkedin = "gianmariaricci"


[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Articoli"
weight = -15
identifier = "posts"
url = "/post/"

[[menu.main]]
name = "Categorie"
weight = -10
identifier = "Categories"
url = "/categories/"

[[menu.main]]
name = "Blog inglese"
weight = -20
identifier = "english"
url = "https://www.codewrecks.com/"

[languages]
  [languages.it]
  languageCode = "it"
  languageName = "Italiano"
  weight = 1
